version: '3.8'

services:

  db:
    container_name: teste_guia_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./prisma/sql/:/docker-entrypoint-initdb.d/

  python_app:
    container_name: python_app
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command: ["python", "main.py"]

volumes:
  postgres:
